# <u> Use only those concepts which have been taught till now </u>

In [1]:
import numpy as np

# <u>**Problem 1**</u>

### What is the average value of the first 5 rows of the third and fourth columns?



In [2]:
np.random.seed(21) # This guarantees the code will generate the same set of random numbers whenever executed
random_integers = np.random.randint(1,high=500000, size=(20, 5))
random_integers

array([[ 80842, 333008, 202553, 140037,  81969],
       [ 63857,  42105, 261540, 481981, 176739],
       [489984, 326386, 110795, 394863,  25024],
       [ 38317,  49982, 408830, 485118,  16119],
       [407675, 231729, 265455, 109413, 103399],
       [174677, 343356, 301717, 224120, 401101],
       [140473, 254634, 112262,  25063, 108262],
       [375059, 406983, 208947, 115641, 296685],
       [444899, 129585, 171318, 313094, 425041],
       [188411, 335140, 141681,  59641, 211420],
       [287650,   8973, 477425, 382803, 465168],
       [  3975,  32213, 160603, 275485, 388234],
       [246225,  56174, 244097,   9350, 496966],
       [225516, 273338,  73335, 283013, 212813],
       [ 38175, 282399, 318413, 337639, 379802],
       [198049, 101115, 419547, 260219, 325793],
       [148593, 425024, 348570, 117968, 107007],
       [ 52547, 180346, 178760, 305186, 262153],
       [ 11835, 449971, 494184, 472031, 353049],
       [476442,  35455, 191553, 384154,  29917]])

In [3]:
# Your code here

# Slice the array to get the first 5 rows of the third and fourth columns
slice_array = random_integers[:5, 2:4]

# Calculate the mean of the slice array
mean_value = np.mean(slice_array)

print("The average value of the first 5 rows of the third and fourth columns is:", mean_value)



The average value of the first 5 rows of the third and fourth columns is: 286058.5


#<u>**Problem 2**</u>

### In this problem, we are going to calculate distances between some pairs of points :

### <u> Measures of distances </u>
* ### Euclidean Distance : The distance between two points $(x_{1},y_{1})$ , $(x_{2},y_{2})$ is defined as :
${\displaystyle d(x,y)={\sqrt {(x_{1}-x_{2})^{2}+(y_{1}-y_{2})^{2}}}.}$

* ### Manhattan Distance : The distance between two points $(x_{1},y_{1})$ , $(x_{2},y_{2})$ is defined as :
${\displaystyle d(x,y)=|x_{1}-x_{2}|+|y_{1}-y_{2}|}$


### Create a 2-D array of 10 points where the x-coordinates and the y-coordinates can take random integral values between 5 and 20.


### Next, create two 1-D arrays(one for  Euclidean distance and the other for  Manhattan distance) for these points


In [4]:
# Create the 10 points

np.random.seed(42)
points = np.random.randint(5, 21, size=(10, 2))
print("Points:\n", points)

Points:
 [[11  8]
 [17 19]
 [15 12]
 [17  9]
 [11 14]
 [ 7 11]
 [15 15]
 [12  9]
 [ 8 12]
 [12  7]]


In [6]:
# Calculate Euclidean distances between these pairs of points (total 10*10 = 100 pairs including self pairs). This should give you a 10*10 2-D array where each value corresponds to the distance between a pair

distances = np.zeros((10, 10))
for i in range(10):
    for j in range(10):
        distances[i, j] = np.sqrt(np.sum((points[i] - points[j])**2))
        
print('Euclidean distances:\n', distances)




Euclidean distances:
 [[ 0.         11.04536102 17.49285568 12.04159458 13.34166406 15.23154621
   7.07106781  5.          3.60555128  7.21110255]
 [11.04536102  0.          8.94427191  1.          4.47213595  7.61577311
   4.47213595 12.52996409  9.8488578   7.07106781]
 [17.49285568  8.94427191  0.          8.54400375 12.16552506 15.03329638
  12.80624847 20.51828453 17.69180601 15.8113883 ]
 [12.04159458  1.          8.54400375  0.          4.12310563  7.28010989
   5.38516481 13.41640786 10.77032961  7.81024968]
 [13.34166406  4.47213595 12.16552506  4.12310563  0.          3.16227766
   6.32455532 13.15294644 11.          7.07106781]
 [15.23154621  7.61577311 15.03329638  7.28010989  3.16227766  0.
   8.60232527 14.03566885 12.36931688  8.24621125]
 [ 7.07106781  4.47213595 12.80624847  5.38516481  6.32455532  8.60232527
   0.          8.06225775  5.38516481  3.16227766]
 [ 5.         12.52996409 20.51828453 13.41640786 13.15294644 14.03566885
   8.06225775  0.          2.82842712

In [7]:
# Calculate Manhattan distances between these pairs of points (total 10*10 = 100 pairs inlcuding self pairs).This should give you a 10*10 2-D array where each value corresponds to the distance between a pair.

manhattan_distances = np.zeros((10, 10))
for i in range(10):
    for j in range(10):
        manhattan_distances[i, j] = abs(points[i, 0] - points[j, 0]) + abs(points[i, 1] - points[j, 1])
        
print(manhattan_distances)



[[ 0. 12. 24. 13. 16. 20.  8.  5.  5. 10.]
 [12.  0. 12.  1.  6. 10.  6. 17. 13. 10.]
 [24. 12.  0. 11. 14. 16. 18. 29. 25. 22.]
 [13.  1. 11.  0.  5.  9.  7. 18. 14. 11.]
 [16.  6. 14.  5.  0.  4.  8. 15. 11.  8.]
 [20. 10. 16.  9.  4.  0. 12. 15. 15. 10.]
 [ 8.  6. 18.  7.  8. 12.  0. 11.  7.  4.]
 [ 5. 17. 29. 18. 15. 15. 11.  0.  4.  7.]
 [ 5. 13. 25. 14. 11. 15.  7.  4.  0.  5.]
 [10. 10. 22. 11.  8. 10.  4.  7.  5.  0.]]


## Find the closest pairs (excluding self pairs) on the basis of both the distance measures

In [9]:
#the code to find the closest pairs based on Euclidean distance:
euclidean_distance = []
for i in range(10):
    for j in range(i+1, 10):
        dist = np.sqrt(np.sum((points[i]-points[j])**2))
        euclidean_distance.append(dist)

# Calculate Manhattan distance between pairs of points
manhattan_distance = []
for i in range(10):
    for j in range(i+1, 10):
        dist = np.sum(np.abs(points[i]-points[j]))
        manhattan_distance.append(dist)

print("Euclidean Distance:", euclidean_distance)
print("Manhattan Distance:", manhattan_distance)

Euclidean Distance: [11.045361017187261, 17.4928556845359, 12.041594578792296, 13.341664064126334, 15.231546211727817, 7.0710678118654755, 5.0, 3.605551275463989, 7.211102550927978, 8.94427190999916, 1.0, 4.47213595499958, 7.615773105863909, 4.47213595499958, 12.529964086141668, 9.848857801796104, 7.0710678118654755, 8.54400374531753, 12.165525060596439, 15.033296378372908, 12.806248474865697, 20.518284528683193, 17.69180601295413, 15.811388300841896, 4.123105625617661, 7.280109889280518, 5.385164807134504, 13.416407864998739, 10.770329614269007, 7.810249675906654, 3.1622776601683795, 6.324555320336759, 13.152946437965905, 11.0, 7.0710678118654755, 8.602325267042627, 14.035668847618199, 12.36931687685298, 8.246211251235321, 8.06225774829855, 5.385164807134504, 3.1622776601683795, 2.8284271247461903, 6.082762530298219, 4.123105625617661]
Manhattan Distance: [12, 24, 13, 16, 20, 8, 5, 5, 10, 12, 1, 6, 10, 6, 17, 13, 10, 11, 14, 16, 18, 29, 25, 22, 5, 9, 7, 18, 14, 11, 4, 8, 15, 11, 8, 12

# <u>**Problem 3**</u>

## Extract all the contiguous 3x3 blocks from a random 10x10 matrix. For example, the first matrix corresponds to [:3,:3], then the second matrix corresponds to [:3,1:4],.... Once you have covered the first three rows, then the next set of matrices would be [1:4,:3],[1:4,1:4],.... and so on and so forth. The last matrix would be [7:10,7:10]

In [12]:
# Your code below ..


random_matrix = np.random.randint(1, high=100, size=(10,10))

blocks = []

for i in range(8):
    for j in range(8):
        blocks.append(random_matrix[i:i+3, j:j+3])


for block in blocks:
    print(block)







[[49 85 60]
 [51 57 99]
 [13 83 16]]
[[85 60 21]
 [57 99 49]
 [83 16  7]]
[[60 21 77]
 [99 49 54]
 [16  7 85]]
[[21 77 57]
 [49 54  6]
 [ 7 85 91]]
[[77 57 42]
 [54  6 81]
 [85 91 29]]
[[57 42  6]
 [ 6 81 36]
 [91 29 10]]
[[42  6 19]
 [81 36 92]
 [29 10 81]]
[[ 6 19 71]
 [36 92 34]
 [10 81  1]]
[[51 57 99]
 [13 83 16]
 [ 6 70 58]]
[[57 99 49]
 [83 16  7]
 [70 58  5]]
[[99 49 54]
 [16  7 85]
 [58  5 77]]
[[49 54  6]
 [ 7 85 91]
 [ 5 77 31]]
[[54  6 81]
 [85 91 29]
 [77 31 31]]
[[ 6 81 36]
 [91 29 10]
 [31 31 77]]
[[81 36 92]
 [29 10 81]
 [31 77 26]]
[[36 92 34]
 [10 81  1]
 [77 26 33]]
[[13 83 16]
 [ 6 70 58]
 [91 33 64]]
[[83 16  7]
 [70 58  5]
 [33 64 26]]
[[16  7 85]
 [58  5 77]
 [64 26 80]]
[[ 7 85 91]
 [ 5 77 31]
 [26 80 54]]
[[85 91 29]
 [77 31 31]
 [80 54 67]]
[[91 29 10]
 [31 31 77]
 [54 67 72]]
[[29 10 81]
 [31 77 26]
 [67 72 34]]
[[10 81  1]
 [77 26 33]
 [72 34  9]]
[[ 6 70 58]
 [91 33 64]
 [59 51 95]]
[[70 58  5]
 [33 64 26]
 [51 95 25]]
[[58  5 77]
 [64 26 80]
 [95 25 26]]
[

#<u>**Problem 4**</u>

### Write a function which finds the nearest value from a given value in an array of random N elements. Suppose you created an 1-D array with 15 elements taking values between 10 and 500. Your function would take any input from these values and return the nearest value. (You can use np.abs() function)

In [16]:
# Your function below

def find_nearest_value(arr, val):
    idx = (np.abs(arr - val)).argmin()
    return arr[idx]

val = 100
arr = np.random.randint(10, 500, size=15)
print(arr)
nearest_val = find_nearest_value(arr, val)
print(f"Nearest value to {val}: {nearest_val}")

[247 291 130 429  20 339  78  38 154  44  51  10 194 168 472]
Nearest value to 100: 78
